import { BRAND_THEMES, DEFAULT_BRAND_THEME, normalizeBrandTheme } from "./brand-themes.js";

const STORAGE_KEY = "toastyBrandProfiles";

const PROFILE_DEFAULTS = {
  description: "",
  creatorName: "",
  creatorTitle: "",
  creatorHandle: "",
  logos: [],
  watermark: true,
  introAsset: "",
  outroAsset: "",
  defaultCTA: "",
  website: "",
  lowerThird: "",
  backgroundPreference: "",
  fontDirection: "",
  visualStyle: "",
  toneOfVoice: "",
  writingStyle: "",
  captionStyle: "",
  lowerThirdStyle: "",
  introStyle: "",
  outroStyle: "",
  ctaStyle: "",
  musicDirection: "",
  musicAsset: "",
  musicVolume: 0.12,
  defaultAspectRatio: "16:9",
  introDuration: 1.6,
  outroDuration: 2.4,
  avatarPreference: "",
  cameraDirection: "",
  thumbnailDirection: "",
  forbiddenStyles: [],
  preferredPhrases: [],
  avoidPhrases: [],
  platformPreferences: {},
  notes: "",
  conciergePrefix: ""
};

const DEFAULT_PROFILES = Object.freeze({
  toasty: Object.freeze({
    id: "toasty",
    name: "Toasty Media",
    description: "Warm, clever, high-energy creative production for ideas that need to feel human and worth watching.",
    creatorName: "Ricardo Casanova",
    creatorTitle: "Founder / Toasty Media",
    creatorHandle: "@ricardocasanova",
    logos: ["../shared/brand/toasty-media/ToastyMediaStudio.png"],
    watermark: true,
    defaultCTA: "Connect with Ricardo",
    website: "toasty.media",
    lowerThird: "Ricardo Casanova · Founder / Toasty Media",
    primaryColor: "#ff7a29",
    secondaryColor: "#ffc670",
    accentColor: "#ffab5c",
    backgroundPreference: "dark studio canvas with orange/fire glow and warm paper writing surfaces",
    fontDirection: "bold Montserrat headlines with readable Inter body text",
    visualStyle: "cinematic studio energy, firelight accents, practical creator-led visuals, minimal clutter",
    toneOfVoice: "energetic, warm, punchy, opinionated, useful",
    writingStyle: "short sentences, strong hooks, concrete proof, no corporate fog",
    captionStyle: "minimal text, high contrast, punchy lines that do not crowd the frame",
    lowerThirdStyle: "compact dark lower thirds with Toasty orange accent line",
    introStyle: "start immediately with the strongest human line",
    outroStyle: "land on a useful takeaway, not a generic sign-off",
    ctaStyle: "direct and practical with one clear next move",
    musicDirection: "warm pulse, light momentum, never overpowering the voice",
    defaultAspectRatio: "16:9",
    introDuration: 1.6,
    outroDuration: 2.4,
    avatarPreference: "creator digital twin driven by real recorded narration",
    cameraDirection: "confident eye-line, subtle punch-ins, avoid static talking head fatigue",
    thumbnailDirection: "bold face or object, orange contrast, 3-5 words max",
    forbiddenStyles: ["generic robot visuals", "cold SaaS gradients", "dense text slides", "AI voiceover"],
    preferredPhrases: ["worth watching", "make it real", "show the proof"],
    avoidPhrases: ["unlock synergy", "leverage cutting-edge", "AI-powered solution"],
    platformPreferences: {
      LinkedIn: { pacing: "polished and concise", targetDuration: 60, aspectRatio: "4:5" },
      "YouTube Shorts": { pacing: "fast hook, clean payoff", targetDuration: 45, aspectRatio: "9:16" },
      "Instagram Reels": { pacing: "visual and punchy", targetDuration: 35, aspectRatio: "9:16" },
      TikTok: { pacing: "direct and immediate", targetDuration: 30, aspectRatio: "9:16" },
      YouTube: { pacing: "structured and clear", targetDuration: 120, aspectRatio: "16:9" },
      Generic: { pacing: "tight and useful", targetDuration: 45, aspectRatio: "9:16" }
    },
    notes: "Preserve the creator's real narration as the source of truth.",
    conciergePrefix: "Toasty suggests:"
  }),
  "8alta": Object.freeze({
    id: "8alta",
    name: "8alta",
    description: "Premium executive production with quiet confidence and precise delivery.",
    creatorName: "8alta",
    creatorTitle: "Executive AI Strategy",
    logos: ["https://www.8alta.com/assets/8alta-logo-gold-transparent.png"],
    watermark: true,
    defaultCTA: "Book a strategic conversation",
    website: "8alta.com",
    lowerThird: "8alta · Executive AI Strategy",
    primaryColor: "#c8a45d",
    secondaryColor: "#f5f1e8",
    accentColor: "#d8c17e",
    supportingPalette: ["#07111f", "#111d2d", "#d8dee6", "#f5f1e8"],
    backgroundPreference: "deep midnight navy production environment with warm ivory type and restrained gold accents",
    fontDirection: "bold executive headings, crisp professional body text, measured spacing",
    visualStyle: "premium advisory, composed, evidence-led, light navy and gold hierarchy, minimal ornament",
    toneOfVoice: "authoritative, calm, precise, executive",
    writingStyle: "clear claims, measured confidence, boardroom-ready language",
    captionStyle: "restrained captions with generous spacing",
    lowerThirdStyle: "minimal dark lower thirds with gold accent",
    introStyle: "lead with a sharp executive problem",
    outroStyle: "close with a strategic decision or next action",
    ctaStyle: "measured invitation to act with clarity",
    musicDirection: "subtle premium pulse",
    defaultAspectRatio: "16:9",
    introDuration: 1.6,
    outroDuration: 2.4,
    avatarPreference: "polished creator avatar driven by real narration",
    cameraDirection: "steady, frontal, composed",
    thumbnailDirection: "high contrast, premium restraint, no visual noise",
    forbiddenStyles: ["cartoon visuals", "hype language", "busy captions", "AI voiceover"],
    preferredPhrases: ["clear decision", "production proof", "executive signal"],
    avoidPhrases: ["viral hack", "crazy", "game changer"],
    platformPreferences: {},
    notes: "Use sparing visual emphasis.",
    conciergePrefix: "8ALTA Studio suggests:"
  }),
  santati: Object.freeze({
    id: "santati",
    name: "Santati",
    description: "Trust-building, nature-aligned production with clarity and grounded warmth.",
    creatorName: "Santati",
    creatorTitle: "Trust-centered CRM",
    logos: ["https://www.santaticrm.com/assets/santati-logo-only-white.png"],
    watermark: true,
    defaultCTA: "Start with a clear next step",
    website: "santaticrm.com",
    lowerThird: "Santati · Trust-centered CRM",
    primaryColor: "#6f45ff",
    secondaryColor: "#18d8c0",
    accentColor: "#ff4fc3",
    supportingPalette: ["#17112d", "#21183c", "#89f5e8", "#f7f7fb"],
    backgroundPreference: "Santati purple production environment with teal clarity accents and soft luminous surfaces",
    fontDirection: "clean readable type with grounded spacing and warm high-contrast headings",
    visualStyle: "purple and teal trust system, calm, trustworthy, human-centered, softly dimensional",
    toneOfVoice: "grounded, warm, clear, reassuring",
    writingStyle: "plain language, gentle authority, practical examples",
    captionStyle: "clear captions with soft contrast and natural pacing",
    lowerThirdStyle: "clean lower thirds with green accent",
    introStyle: "begin with a relatable human need",
    outroStyle: "end with confidence and care",
    ctaStyle: "supportive, specific, low-friction",
    musicDirection: "light organic bed, calm momentum",
    defaultAspectRatio: "16:9",
    introDuration: 1.6,
    outroDuration: 2.4,
    avatarPreference: "natural creator avatar driven by real narration",
    cameraDirection: "warm eye-line, soft movement",
    thumbnailDirection: "natural contrast, human warmth",
    forbiddenStyles: ["harsh glitch effects", "robot visuals", "fear-based copy", "AI voiceover"],
    preferredPhrases: ["with care", "clear next step", "built on trust"],
    avoidPhrases: ["disrupt", "dominate", "crush it"],
    platformPreferences: {},
    notes: "Favor trust and clarity over urgency.",
    conciergePrefix: "Santati Studio suggests:"
  }),
  optimai: Object.freeze({
    id: "optimai",
    name: "OptimAI Network",
    description: "Agent-native decentralized intelligence with a precise, technical, high-contrast visual system.",
    creatorName: "OptimAI Network",
    creatorTitle: "Decentralized AI Infrastructure",
    logos: ["https://r2-opi-lp.optimai.network/images/branding/main-logo-v2.svg"],
    watermark: true,
    defaultCTA: "Explore the network",
    website: "optimai.network",
    lowerThird: "OptimAI Network · Decentralized AI Infrastructure",
    primaryColor: "#5eed87",
    secondaryColor: "#f6f655",
    accentColor: "#baf46e",
    supportingPalette: ["#0a0a0a", "#121614", "#939393", "#ffffff"],
    backgroundPreference: "near-black technical canvas with lime-to-green signals and subtle network geometry",
    fontDirection: "Plus Jakarta Sans with light technical headlines and compact interface labels",
    visualStyle: "agent-native infrastructure, dark precision, network topology, restrained neon signal",
    toneOfVoice: "technical, direct, ambitious, credible",
    writingStyle: "short declarative claims backed by concrete infrastructure details",
    captionStyle: "high-contrast white captions with a green signal accent",
    lowerThirdStyle: "minimal black glass lower thirds with lime-to-green edge",
    introStyle: "open on the data, agent, or network outcome",
    outroStyle: "close with one concrete way to join or explore the network",
    ctaStyle: "direct action with technical clarity",
    musicDirection: "minimal electronic pulse with clean transients",
    defaultAspectRatio: "16:9",
    introDuration: 1.4,
    outroDuration: 2.2,
    avatarPreference: "clean technical presenter driven by real narration",
    cameraDirection: "centered, high contrast, deliberate motion",
    thumbnailDirection: "black field, white type, one green network signal",
    forbiddenStyles: ["generic crypto coins", "purple SaaS gradients", "dense token charts", "AI voiceover"],
    preferredPhrases: ["your data", "your agent", "your control", "agent-native"],
    avoidPhrases: ["moon", "guaranteed rewards", "revolutionary solution"],
    platformPreferences: {},
    notes: "Keep the network credible and the visual system sparse.",
    conciergePrefix: "OptimAI Studio suggests:"
  }),
  tangem: Object.freeze({
    id: "tangem",
    name: "Tangem",
    description: "Premium, restrained security/fintech production — black-dominant, precise, no crypto-neon cliche.",
    creatorName: "Tangem",
    creatorTitle: "Secure Hardware & Crypto Wallet",
    logos: [],
    watermark: true,
    defaultCTA: "See how Tangem secures your keys",
    website: "tangem.com",
    lowerThird: "Tangem",
    primaryColor: "#0099ff",
    secondaryColor: "#ffffff",
    accentColor: "#33aaff",
    supportingPalette: ["#000000", "#0d0d0f", "#6c6c70", "#ffffff"],
    backgroundPreference: "black-dominant production environment with restrained Tangem-blue signal accents",
    fontDirection: "clean geometric sans headlines, precise and unadorned body text",
    visualStyle: "premium minimal security aesthetic, high contrast black/white, single disciplined blue accent, no ornament",
    toneOfVoice: "precise, calm, confident, security-first",
    writingStyle: "short declarative claims, no hype, concrete and verifiable",
    captionStyle: "high-contrast white captions, minimal, no crowding",
    lowerThirdStyle: "minimal black lower thirds with a single blue accent line",
    introStyle: "open on the concrete security/product outcome",
    outroStyle: "close with one precise, verifiable next step",
    ctaStyle: "direct, unembellished, trustworthy",
    musicDirection: "minimal, restrained, no cliche crypto energy",
    defaultAspectRatio: "16:9",
    introDuration: 1.6,
    outroDuration: 2.4,
    avatarPreference: "clean presenter driven by real narration",
    cameraDirection: "steady, centered, composed",
    thumbnailDirection: "black field, white type, one blue signal, no clutter",
    forbiddenStyles: ["crypto-neon gradients", "generic coin graphics", "hype language", "AI voiceover"],
    preferredPhrases: ["your keys", "verifiable security", "built to last"],
    avoidPhrases: ["moon", "guaranteed returns", "revolutionary", "to the moon"],
    platformPreferences: {},
    notes: "Restraint is the brand. When unsure, remove an element rather than add one.",
    conciergePrefix: "Tangem Studio suggests:"
  }),
  superteam: Object.freeze({
    id: "superteam",
    name: "Superteam Thailand",
    description: "Premium, energetic, technical Solana-ecosystem production for Superteam Thailand builders.",
    creatorName: "Superteam Thailand",
    creatorTitle: "Solana Builders · APAC",
    logos: ["../shared/brand/clients/superteam-thailand/logo.png"],
    watermark: true,
    defaultCTA: "Build with Superteam Thailand",
    website: "th.superteam.fun",
    lowerThird: "Superteam Thailand · Solana Builders",
    primaryColor: "#9945ff",
    secondaryColor: "#14f195",
    accentColor: "#00e5ff",
    supportingPalette: ["#070b1c", "#10183a", "#14f195", "#f4f7ff"],
    backgroundPreference: "deep navy production environment with Solana purple/green signal accents and restrained cyan highlights",
    fontDirection: "clean technical Inter headlines and compact professional body text",
    visualStyle: "premium builder energy, dark navy, Solana-inspired purple-to-green hierarchy, no tourist ornament",
    toneOfVoice: "energetic, technical, credible, community-first",
    writingStyle: "short declarative builder language, concrete, no hype",
    captionStyle: "high-contrast captions with a single purple or cyan accent",
    lowerThirdStyle: "minimal navy lower thirds with Solana purple accent line",
    introStyle: "open on the build, the community, or the APAC outcome",
    outroStyle: "close with one concrete way to build together",
    ctaStyle: "direct invitation to build or join Superteam Thailand",
    musicDirection: "energetic technical pulse, never carnival or tourist",
    defaultAspectRatio: "16:9",
    introDuration: 1.5,
    outroDuration: 2.3,
    avatarPreference: "confident builder presenter driven by real narration",
    cameraDirection: "centered, high energy, deliberate motion",
    thumbnailDirection: "navy field, white type, one purple or cyan signal",
    forbiddenStyles: ["temple tourist kitsch", "generic coin rain", "hype language", "AI voiceover"],
    preferredPhrases: ["build together", "power APAC", "ship the story"],
    avoidPhrases: ["moon", "guaranteed returns", "to the moon"],
    platformPreferences: {},
    notes: "Thai identity lives in the Superteam Thailand mark, not in decorative UI.",
    conciergePrefix: "Superteam Thailand Studio suggests:"
  }),
  alice: Object.freeze({
    id: "alice",
    name: "Alice in Cryptoland",
    description: "Playful but professional crypto/Web3 production for interviews, education, livestreams, and social.",
    creatorName: "Alice in Cryptoland",
    creatorTitle: "Curiosity Pays",
    logos: ["../shared/brand/clients/alice-cryptoland/logo.png"],
    watermark: true,
    defaultCTA: "Follow. Learn. Explore. Build.",
    website: "",
    lowerThird: "Alice in Cryptoland · Curiosity Pays",
    primaryColor: "#2ec8e0",
    secondaryColor: "#7b6cff",
    accentColor: "#5ee7ff",
    supportingPalette: ["#051820", "#0b2a36", "#7b6cff", "#e8f6fb"],
    backgroundPreference: "deep teal production environment with cyan signals and restrained purple crypto accents",
    fontDirection: "Plus Jakarta Sans headlines with readable professional body text",
    visualStyle: "professional crypto studio, cyan/teal foundation, complementary purple accents, no illustrated Wonderland scenery in the interface",
    toneOfVoice: "curious, clear, playful, professional",
    writingStyle: "inviting questions, concrete explanations, no casino hype",
    captionStyle: "high-contrast captions with a cyan accent and generous spacing",
    lowerThirdStyle: "teal glass lower thirds with cyan accent line",
    introStyle: "open on the question worth following",
    outroStyle: "close with one clear next step to learn or build",
    ctaStyle: "curious invitation with one next move",
    musicDirection: "bright, light momentum, never carnival or meme-coin energy",
    defaultAspectRatio: "16:9",
    introDuration: 1.6,
    outroDuration: 2.4,
    avatarPreference: "approachable presenter driven by real narration",
    cameraDirection: "warm eye-line, slight energy, avoid static talking head fatigue",
    thumbnailDirection: "teal field, cyan type, one purple or gold signal, no clutter",
    forbiddenStyles: ["illustrated Wonderland scenery in chrome", "casino hype", "coin rain", "AI voiceover"],
    preferredPhrases: ["curiosity pays", "follow the idea", "learn then build"],
    avoidPhrases: ["moon", "guaranteed returns", "ngmi"],
    platformPreferences: {},
    notes: "Keep the Studio professional. Alice identity is color, type, and the official lockup — not a themed illustration overlay.",
    conciergePrefix: "Alice in Cryptoland Studio suggests:"
  }),
  peeps: Object.freeze({
    id: "peeps",
    name: "Toasty Peeps",
    description: "Warm, approachable expert-conversation production for people, discovery, bookings, and collaboration.",
    creatorName: "Toasty Peeps",
    creatorTitle: "Human Expertise Network",
    logos: ["../shared/brand/toasty-peeps/logo.png"],
    watermark: true,
    defaultCTA: "Find the people. Keep the conversation.",
    website: "toasty.media",
    lowerThird: "Toasty Peeps · Human Expertise",
    primaryColor: "#e56a1a",
    secondaryColor: "#f4c38a",
    accentColor: "#f08a3a",
    supportingPalette: ["#16100c", "#221812", "#3d2914", "#fbf4ea"],
    backgroundPreference: "warm brown studio canvas with honey-amber accents and cream writing surfaces",
    fontDirection: "bold Montserrat headlines with readable Inter body text",
    visualStyle: "Toasty family DNA with a people-first warmth: conversations, experts, collaboration, less fire-studio intensity",
    toneOfVoice: "warm, human, curious, useful",
    writingStyle: "short sentences, human hooks, concrete introductions, no corporate fog",
    captionStyle: "minimal text, high contrast, conversational lines that do not crowd the frame",
    lowerThirdStyle: "compact warm lower thirds with copper-orange accent line",
    introStyle: "start with the person and why they are in the room",
    outroStyle: "land on a useful next conversation, not a generic sign-off",
    ctaStyle: "direct and human with one clear next move",
    musicDirection: "warm pulse, light momentum, never overpowering the voice",
    defaultAspectRatio: "16:9",
    introDuration: 1.6,
    outroDuration: 2.4,
    avatarPreference: "expert digital twin driven by real recorded narration",
    cameraDirection: "confident eye-line, conversation framing, avoid static talking head fatigue",
    thumbnailDirection: "bold face, warm copper contrast, 3-5 words max",
    forbiddenStyles: ["generic robot visuals", "cold SaaS gradients", "dense text slides", "AI voiceover"],
    preferredPhrases: ["find the people", "keep the conversation", "human expertise"],
    avoidPhrases: ["unlock synergy", "leverage cutting-edge", "thought leader"],
    platformPreferences: {
      LinkedIn: { pacing: "polished and concise", targetDuration: 60, aspectRatio: "4:5" },
      "YouTube Shorts": { pacing: "fast hook, clean payoff", targetDuration: 45, aspectRatio: "9:16" },
      "Instagram Reels": { pacing: "visual and punchy", targetDuration: 35, aspectRatio: "9:16" },
      TikTok: { pacing: "direct and immediate", targetDuration: 30, aspectRatio: "9:16" },
      YouTube: { pacing: "structured and clear", targetDuration: 120, aspectRatio: "16:9" },
      Generic: { pacing: "tight and useful", targetDuration: 45, aspectRatio: "9:16" }
    },
    notes: "Toasty Studio produces media. Toasty Peeps produces people and expertise. Keep that distinction in copy and framing.",
    conciergePrefix: "Toasty Peeps suggests:"
  })
});

export function getBrandProfiles() {
  const saved = readSavedProfiles();
  const profileIds = new Set([...Object.keys(DEFAULT_PROFILES), ...Object.keys(BRAND_THEMES), ...Object.keys(saved)]);
  return [...profileIds].map((id) => {
    const theme = BRAND_THEMES[normalizeBrandTheme(id)];
    return mergeProfile(DEFAULT_PROFILES[id] || (theme ? profileFromTheme(theme) : blankProfile(id)), saved[id]);
  });
}

export function getBrandProfile(profileId = DEFAULT_BRAND_THEME) {
  const normalized = normalizeBrandTheme(profileId);
  return getBrandProfiles().find((profile) => profile.id === normalized) || getBrandProfiles()[0];
}

export function saveBrandProfile(profile) {
  const profiles = readSavedProfiles();
  profiles[profile.id] = mergeProfile(getBrandProfile(profile.id), profile);
  localStorage.setItem(STORAGE_KEY, JSON.stringify(profiles));
  return profiles[profile.id];
}

function readSavedProfiles() {
  try {
    return JSON.parse(localStorage.getItem(STORAGE_KEY) || "{}");
  } catch {
    return {};
  }
}

function profileFromTheme(theme) {
  return {
    ...PROFILE_DEFAULTS,
    id: theme.id,
    name: theme.label,
    logos: theme.logoSrc ? [theme.logoSrc] : [],
    primaryColor: theme.vars["--studio-orange"],
    secondaryColor: theme.vars["--studio-amber"],
    accentColor: theme.vars["--studio-orange-bright"],
    visualStyle: `${theme.label} studio style`,
    toneOfVoice: "clear, useful, brand-consistent",
    writingStyle: "concise and direct",
    captionStyle: "readable, high contrast",
    ctaStyle: "one clear next step",
    conciergePrefix: theme.copy?.conciergePrefix || `${theme.label} Studio suggests:`
  };
}

function blankProfile(id) {
  return {
    ...PROFILE_DEFAULTS,
    id,
    name: id,
    primaryColor: "#ff7a29",
    secondaryColor: "#ffc670",
    accentColor: "#ffab5c"
  };
}

function mergeProfile(base, override = {}) {
  return {
    ...PROFILE_DEFAULTS,
    ...base,
    ...override,
    platformPreferences: {
      ...(base?.platformPreferences || {}),
      ...(override?.platformPreferences || {})
    }
  };
}
