import { ToastyBroadcastController } from "./broadcast-client.js";
import { studioApiEndpoint } from "./studio-api.js";
const $=s=>document.querySelector(s); let screen=null,cam=null,mic=null,rec=null,chunks=[],started=0,marks=[];
async function auth(){try{const r=await fetch(studioApiEndpoint()+"/auth/session",{credentials:"include"});const j=await r.json();if(!j.authenticated) location.href="./sessions.html";}catch{location.href="./sessions.html"}}
auth();
$("[data-mode='voiceover']").onclick=()=>$("#voiceoverFile").click();
document.querySelectorAll("[data-mode]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-mode]").forEach(x=>x.classList.remove("active"));b.classList.add("active");if(b.dataset.mode==="voiceover")$("#voiceoverFile").click()});
$("#captureBtn").onclick=async()=>{screen=await navigator.mediaDevices.getDisplayMedia({video:{frameRate:{ideal:30,max:60}},audio:true,systemAudio:"include",surfaceSwitching:"include"});$("#screenPreview").srcObject=screen;$("#stageEmpty").hidden=true;setStatus("Game / screen captured.");screen.getVideoTracks()[0]?.addEventListener("ended",()=>{screen=null;$("#screenPreview").srcObject=null;setStatus("Capture ended.")})};
$("#cameraBtn").onclick=async()=>{if(cam){cam.getTracks().forEach(t=>t.stop());cam=null;$("#cameraPreview").srcObject=null;return}cam=await navigator.mediaDevices.getUserMedia({video:true,audio:false});$("#cameraPreview").srcObject=cam;$("#stage").classList.add("game-camera")};
$("#micBtn").onclick=async()=>{if(mic){mic.getTracks().forEach(t=>t.stop());mic=null;setStatus("Mic off.");return}mic=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:false},video:false});setStatus("Mic ready.")};
document.querySelectorAll("[data-scene]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-scene]").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("#stage").className="stage "+(b.dataset.scene==="brb"?"brB":b.dataset.scene)});
$("#voiceoverFile").onchange=e=>{const f=e.target.files[0];if(!f)return;const v=$("#voiceoverPreview");v.src=URL.createObjectURL(f);v.hidden=false;setStatus("Voiceover video loaded. Turn on Mic, then Record.")};
$("#recordBtn").onclick=async()=>{if(rec&&rec.state!=="inactive"){rec.stop();return}if(!screen&&!$("#voiceoverPreview").src) return setStatus("Capture a game/screen or load a voiceover video first.");if(!mic) await $("#micBtn").onclick();const source=screen||$("#voiceoverPreview").captureStream?.();if(!source)return setStatus("This browser cannot capture the loaded video.");const ctx=new AudioContext(),dest=ctx.createMediaStreamDestination();for(const s of [source,mic])for(const t of s?.getAudioTracks?.()||[])ctx.createMediaStreamSource(new MediaStream([t])).connect(dest);const combined=new MediaStream([...source.getVideoTracks(),...dest.stream.getAudioTracks()]);chunks=[];marks=[];started=Date.now();rec=new MediaRecorder(combined,{mimeType:MediaRecorder.isTypeSupported("video/webm;codecs=vp9,opus")?"video/webm;codecs=vp9,opus":"video/webm"});rec.ondataavailable=e=>e.data.size&&chunks.push(e.data);rec.onstop=()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(chunks,{type:rec.mimeType}));a.download="toasty-creator-"+new Date().toISOString().replace(/[:.]/g,"-")+".webm";a.click();$("#recordBtn").classList.remove("on");$("#recordBtn").textContent="Record";$("#markBtn").disabled=true;setStatus("Recording saved.")};rec.start(1000);$("#recordBtn").classList.add("on");$("#recordBtn").textContent="Stop";$("#markBtn").disabled=false;setStatus("Recording…")};
$("#markBtn").onclick=()=>{const sec=((Date.now()-started)/1000).toFixed(1);marks.push(sec);$("#clips").textContent=marks.map((m,i)=>"Clip "+(i+1)+" · "+m+"s").join("\n");};
$("#voiceoverPreview").onplay=()=>setStatus("Voiceover playback running.");
const bc=new ToastyBroadcastController({getProgramUrl:()=>location.href,requireLegacyAuthGate:false,onStateChange:s=>{$("#liveBtn").classList.toggle("on",s==="live")}}).init();
const panel=$("#broadcastPanel");$("#broadcastMount").appendChild(panel);$("#liveBtn").onclick=()=>{panel.hidden=!panel.hidden};$("#openProgramOutput").hidden=true;
function setStatus(s){$("#status").textContent=s}
