const seed=[
{name:'Maya Chen',role:'Infrastructure strategy operator',topics:['ai infrastructure','data centers','southeast asia','procurement','cloud','energy','expert panel'],evidence:['12 years in regional infrastructure strategy','Recent data-center procurement work','Frequent executive speaker'],dub:.001},
{name:'Amina Patel',role:'Biotech researcher and founder',topics:['biotech','healthcare','research','founder','expert panel'],evidence:['Peer-reviewed research background','Founder/operator experience','Translates technical topics for general audiences'],dub:.001},
{name:'Nok S.',role:'Bangkok parent · household purchaser',topics:['bangkok','parent','children','groceries','household','toyota','japanese cars','streaming','focus group','consumer'],evidence:['Approved participant profile includes household purchasing','Vehicle ownership and Bangkok location are matchable','Open to paid focus groups and concept tests'],dub:.001},
{name:'Claire M.',role:'Working parent · SUV owner',topics:['parent','family','suv','vehicle','grocery','netflix','streaming','consumer','focus group'],evidence:['Approved family and vehicle context','Frequent household purchase decision-maker','Comfortable in moderated video research'],dub:.001},
{name:'Kenji T.',role:'Gamer · technology buyer',topics:['gaming','consumer electronics','pc','mobile','subscriptions','product test','focus group'],evidence:['Approved gaming and purchase-interest context','Open to product and concept testing','Prior moderated research participation'],dub:.001},
{name:'Daniel Okafor',role:'Former hyperscaler procurement lead',topics:['diligence','institutional research','expert jam','cloud','pricing','procurement','data centers','confidential'],evidence:['10+ years buying cloud and data-center capacity','Comfortable with compliance-screened expert Jams','Can speak to vendor pricing dynamics'],dub:.001},
{name:'Priya Nair',role:'Fintech founder · storyteller',topics:['podcast guest','fintech','founder','payments','southeast asia','storytelling','speaker'],evidence:['Founded and scaled a payments company','Regular conference and podcast speaker','Translates complex topics for general audiences'],dub:.001},
{name:'Lena Fischer',role:'VP Operations · B2B SaaS buyer',topics:['market fit','customer discovery','buyer','saas','pricing','finance','budget owner','customer conversation'],evidence:['Owns budget for finance-ops tooling','Open to paid customer-discovery Jams','Has evaluated and switched vendors'],dub:.001},
{name:'Marcus Reed',role:'Digital assets infrastructure operator',topics:['crypto','solana','distributed systems','payments','web3','ai agents','expert panel'],evidence:['Production infrastructure experience','Agent/payment systems focus','Conference speaker'],dub:.001}
];
const $=s=>document.querySelector(s);const tokenize=v=>new Set(v.toLowerCase().replace(/[^a-z0-9\s]/g,' ').split(/\s+/).filter(x=>x.length>2));
function score(p,q){const stop=new Set(['the','and','for','who','our','can','with','own','you','are','this','that','from','tell','great','about','shipped','have','has','ten','eight','three']);const a=[...tokenize(q)].filter(x=>!stop.has(x)),b=tokenize([p.role,...p.topics,...p.evidence].join(' '));let hits=0;a.forEach(t=>{if(b.has(t)||[...b].some(x=>x.length>3&&t.length>3&&(x.includes(t)||t.includes(x))))hits++});const ratio=hits/Math.max(4,Math.min(a.length,8));return Math.round(Math.max(28,Math.min(96,34+ratio*70)));}
function verdict(n){return n>=80?'Yes':n>=62?'Close':'No'}
function find(){const brief=$('#brief').value.trim();if(!brief)return;const q=`${brief} ${$('#intent').value} ${$('#context').value}`;const list=seed.map(p=>({...p,score:score(p,q)})).sort((a,b)=>b.score-a.score);$('#count').textContent=list.length;$('#strong').textContent=list.filter(p=>p.score>=62).length;$('#results').innerHTML=list.map((p,i)=>`<article class="card peep"><div class="top"><div><h3>${p.name}</h3><small>${p.role}</small></div><b class="verdict v-${verdict(p.score).toLowerCase()}">${verdict(p.score)} · ${p.score}%</b></div><p>${p.evidence.slice(0,2).join(' · ')}</p><div class="crumbs">${p.topics.slice(0,4).map(t=>`<span>${t}</span>`).join('')}</div><footer><button data-dub="${i}">Make the Call</button><button class="secondary">Invite to Jam</button></footer></article>`).join('');$('#resultsWrap').hidden=false;document.querySelectorAll('[data-dub]').forEach(b=>b.onclick=()=>openDub(list[+b.dataset.dub]));}
function openDub(p){$('#dubBody').innerHTML=`<small>THE CALL · $${p.dub.toFixed(3)} USDC</small><h2>${p.name}</h2><p><b>${verdict(p.score)} · ${p.score}% confident</b> · ${p.role}</p>${p.evidence.map(e=>`<div class="answer"><b>Approved / supported</b><p>${e}</p></div>`).join('')}<div class="answer unknown"><b>Private stays private</b><p>Anything outside approved matchable context remains unknown or requires direct participant consent.</p></div><button>Spend Dough & make the Call</button>`;$('#dub').showModal();}
$('#find').onclick=find;$('#close').onclick=()=>$('#dub').close();
document.querySelectorAll('.chip').forEach(c=>c.onclick=()=>{$('#brief').value=c.dataset.brief;$('#context').value=c.dataset.context;$('#intent').value=c.dataset.intent;document.querySelectorAll('.chip').forEach(x=>x.classList.toggle('on',x===c));find();});
