const seed=[
{name:'Maya Chen',role:'Infrastructure strategy operator',topics:['ai infrastructure','data centers','southeast asia','procurement','cloud','energy','expert panel'],evidence:['12 years in regional infrastructure strategy','Recent data-center procurement work','Frequent executive speaker'],dub:.001},
{name:'Amina Patel',role:'Biotech researcher and founder',topics:['biotech','healthcare','research','founder','expert panel'],evidence:['Peer-reviewed research background','Founder/operator experience','Translates technical topics for general audiences'],dub:.001},
{name:'Nok S.',role:'Bangkok parent · household purchaser',topics:['bangkok','parent','children','groceries','household','toyota','japanese cars','streaming','focus group','consumer'],evidence:['Approved participant profile includes household purchasing','Vehicle ownership and Bangkok location are matchable','Open to paid focus groups and concept tests'],dub:.001},
{name:'Claire M.',role:'Working parent · SUV owner',topics:['parent','family','suv','vehicle','grocery','netflix','streaming','consumer','focus group'],evidence:['Approved family and vehicle context','Frequent household purchase decision-maker','Comfortable in moderated video research'],dub:.001},
{name:'Kenji T.',role:'Gamer · technology buyer',topics:['gaming','consumer electronics','pc','mobile','subscriptions','product test','focus group'],evidence:['Approved gaming and purchase-interest context','Open to product and concept testing','Prior moderated research participation'],dub:.001},
{name:'Marcus Reed',role:'Digital assets infrastructure operator',topics:['crypto','solana','distributed systems','payments','web3','ai agents','expert panel'],evidence:['Production infrastructure experience','Agent/payment systems focus','Conference speaker'],dub:.001}
];
const $=s=>document.querySelector(s);const tokenize=v=>new Set(v.toLowerCase().replace(/[^a-z0-9\s]/g,' ').split(/\s+/).filter(x=>x.length>2));
function score(p,q){const a=tokenize(q),b=tokenize([p.role,...p.topics,...p.evidence].join(' '));let hits=0;a.forEach(t=>{if(b.has(t)||[...b].some(x=>x.includes(t)||t.includes(x)))hits++});return Math.max(48,Math.min(96,52+hits*9+p.evidence.length*3));}
function find(){const brief=$('#brief').value.trim();if(!brief)return;const q=`${brief} ${$('#intent').value} ${$('#context').value}`;const list=seed.map(p=>({...p,score:score(p,q)})).sort((a,b)=>b.score-a.score);$('#count').textContent=list.length;$('#strong').textContent=list.filter(p=>p.score>=70).length;$('#results').innerHTML=list.map((p,i)=>`<article class="card peep"><div class="top"><div><h3>${p.name}</h3><small>${p.role}</small></div><b>${p.score}%</b></div><p>${p.evidence.slice(0,2).join(' · ')}</p><div class="crumbs">${p.topics.slice(0,4).map(t=>`<span>${t}</span>`).join('')}</div><footer><button data-dub="${i}">Ask Dub · $${p.dub.toFixed(3)}</button><button class="secondary">Invite to session</button></footer></article>`).join('');$('#resultsWrap').hidden=false;document.querySelectorAll('[data-dub]').forEach(b=>b.onclick=()=>openDub(list[+b.dataset.dub]));}
function openDub(p){$('#dubBody').innerHTML=`<small>DUB SCREENING · $${p.dub.toFixed(3)} USDC</small><h2>${p.name}</h2><p><b>${p.score}% match</b> · ${p.role}</p>${p.evidence.map(e=>`<div class="answer"><b>Approved / supported</b><p>${e}</p></div>`).join('')}<div class="answer unknown"><b>Private stays private</b><p>Anything outside approved matchable context remains unknown or requires direct participant consent.</p></div><button>Spend Dough & ask this Dub</button>`;$('#dub').showModal();}
$('#find').onclick=find;$('#close').onclick=()=>$('#dub').close();